import esbuild from "esbuild";
import { builtinModules } from "node:module";

const production = process.argv[2] === "production";

const context = await esbuild.context({
    banner: {
        js: "/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */"
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: ["obsidian", "electron", "@codemirror/state", "@codemirror/view", ...builtinModules],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: production ? false : "inline",
    treeShaking: true,
    outfile: "main.js"
});

if (production) {
    await context.rebuild();
    await context.dispose();
} else {
    await context.watch();
}