/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => HunspellSpellcheckerPlugin,
  forceUpdateEffect: () => forceUpdateEffect
});
module.exports = __toCommonJS(main_exports);
var import_state = require("@codemirror/state");
var import_view = require("@codemirror/view");
var import_obsidian2 = require("obsidian");

// src/hunspell.ts
var WORD_SEPARATOR = "/";
var HunspellDictionary = class _HunspellDictionary {
  constructor(affixes) {
    this.rootWords = /* @__PURE__ */ new Map();
    this.lowerRootWords = /* @__PURE__ */ new Map();
    this.flatSuffixes = [];
    this.flatPrefixes = [];
    this.affixes = affixes;
    for (const [flag, rules] of affixes.suffixes.entries()) {
      for (const rule of rules) {
        this.flatSuffixes.push({ flag, rule });
      }
    }
    for (const [flag, rules] of affixes.prefixes.entries()) {
      for (const rule of rules) {
        this.flatPrefixes.push({ flag, rule });
      }
    }
  }
  static async fromFiles(files, onProgress) {
    if (onProgress)
      onProgress("Parsing affixes...");
    const affixes = parseAffixes(files.aff);
    await new Promise((resolve) => setTimeout(resolve, 0));
    if (onProgress)
      onProgress("Parsing dictionary file...");
    const parsedWords = parseDictionary(files.dic, affixes.flagMode);
    const dict = new _HunspellDictionary(affixes);
    const CHUNK_SIZE = 5e3;
    const total = parsedWords.length;
    for (let i = 0; i < total; i += CHUNK_SIZE) {
      if (onProgress && i % (CHUNK_SIZE * 3) === 0) {
        onProgress(`Loading roots... ${Math.round(i / total * 100)}%`);
      }
      const chunk = parsedWords.slice(i, i + CHUNK_SIZE);
      for (const parsed of chunk) {
        dict.addRootWord(parsed);
      }
      await new Promise((resolve) => setTimeout(resolve, 0));
    }
    if (onProgress)
      onProgress("Dictionary loaded");
    return dict;
  }
  has(word) {
    const normalized = this.normalizeWord(word);
    if (!normalized) {
      return true;
    }
    if (this.rootWords.has(normalized) || this.lowerRootWords.has(normalized.toLocaleLowerCase())) {
      return true;
    }
    if (normalized.includes("-")) {
      return normalized.split("-").every((part) => this.has(part));
    }
    const lowerNormalized = normalized.toLocaleLowerCase();
    return this.checkAffixes(normalized) || this.checkAffixes(lowerNormalized);
  }
  suggest(word, limit = 8) {
    const normalized = this.normalizeWord(word);
    if (!normalized || this.has(normalized)) {
      return [];
    }
    const candidates = /* @__PURE__ */ new Set();
    for (const candidate of this.buildReplacementCandidates(normalized)) {
      this.addSuggestionIfValid(candidates, candidate);
    }
    for (const candidate of this.buildMapCandidates(normalized)) {
      this.addSuggestionIfValid(candidates, candidate);
    }
    for (const candidate of this.buildEditCandidates(normalized)) {
      this.addSuggestionIfValid(candidates, candidate);
    }
    return Array.from(candidates).sort((left, right) => this.scoreSuggestion(normalized, left) - this.scoreSuggestion(normalized, right)).slice(0, limit).map((candidate) => applyOriginalCasing(word, candidate));
  }
  addRootWord(parsed) {
    const normalized = this.normalizeWord(parsed.word);
    if (!normalized)
      return;
    this.rootWords.set(normalized, parsed.flags);
    this.lowerRootWords.set(normalized.toLocaleLowerCase(), parsed.flags);
  }
  checkAffixes(word) {
    const validSuffixes = [];
    for (let i = 0; i < this.flatSuffixes.length; i++) {
      const s = this.flatSuffixes[i];
      if (!s.rule.add || word.endsWith(s.rule.add)) {
        validSuffixes.push(s);
      }
    }
    const validPrefixes = [];
    for (let i = 0; i < this.flatPrefixes.length; i++) {
      const p = this.flatPrefixes[i];
      if (!p.rule.add || word.startsWith(p.rule.add)) {
        validPrefixes.push(p);
      }
    }
    for (let i = 0; i < validSuffixes.length; i++) {
      const { flag, rule } = validSuffixes[i];
      const candidateRoot = word.slice(0, word.length - rule.add.length) + rule.strip;
      if (this.hasRootWithFlag(candidateRoot, flag) && rule.condition.test(candidateRoot)) {
        return true;
      }
    }
    for (let i = 0; i < validPrefixes.length; i++) {
      const { flag, rule } = validPrefixes[i];
      const candidateRoot = rule.strip + word.slice(rule.add.length);
      if (this.hasRootWithFlag(candidateRoot, flag) && rule.condition.test(candidateRoot)) {
        return true;
      }
    }
    for (let i = 0; i < validSuffixes.length; i++) {
      const { flag: sFlag, rule: sRule } = validSuffixes[i];
      if (!sRule.crossProduct)
        continue;
      const prefixedWord = word.slice(0, word.length - sRule.add.length) + sRule.strip;
      for (let j = 0; j < validPrefixes.length; j++) {
        const { flag: pFlag, rule: pRule } = validPrefixes[j];
        if (!pRule.crossProduct)
          continue;
        if (pRule.add && !prefixedWord.startsWith(pRule.add))
          continue;
        const candidateRoot = pRule.strip + prefixedWord.slice(pRule.add.length);
        if (this.hasRootWithFlag(candidateRoot, sFlag) && this.hasRootWithFlag(candidateRoot, pFlag)) {
          if (pRule.condition.test(candidateRoot) && sRule.condition.test(prefixedWord)) {
            return true;
          }
        }
      }
    }
    return false;
  }
  hasRootWithFlag(root, flag) {
    const exactFlags = this.rootWords.get(root);
    if (exactFlags && exactFlags.includes(flag))
      return true;
    const lower = root.toLocaleLowerCase();
    const lowerFlags = this.lowerRootWords.get(lower);
    return !!(lowerFlags && lowerFlags.includes(flag));
  }
  addSuggestionIfValid(candidates, candidate) {
    const normalized = this.normalizeWord(candidate);
    if (!normalized || normalized.length < 2) {
      return;
    }
    if (this.has(normalized)) {
      candidates.add(normalized);
    }
  }
  buildReplacementCandidates(word) {
    const candidates = /* @__PURE__ */ new Set();
    for (const replacement of this.affixes.replacements) {
      addStringReplacementCandidates(candidates, word, replacement.from, replacement.to);
      addStringReplacementCandidates(candidates, word, replacement.to, replacement.from);
    }
    return candidates;
  }
  buildMapCandidates(word) {
    const candidates = /* @__PURE__ */ new Set();
    const chars = Array.from(word);
    chars.forEach((char, index) => {
      const lowerChar = char.toLocaleLowerCase();
      const group = this.affixes.maps.find((item) => item.some((mapped) => mapped.toLocaleLowerCase() === lowerChar));
      if (!group) {
        return;
      }
      for (const mapped of group) {
        if (mapped === char) {
          continue;
        }
        const next = [...chars];
        next[index] = preserveCharCasing(char, mapped);
        candidates.add(next.join(""));
      }
    });
    return candidates;
  }
  buildEditCandidates(word) {
    const candidates = /* @__PURE__ */ new Set();
    const chars = Array.from(word);
    const alphabet = this.affixes.tryChars.length ? this.affixes.tryChars : defaultTryChars();
    for (let index = 0; index <= chars.length; index += 1) {
      for (const char of alphabet) {
        candidates.add([...chars.slice(0, index), char, ...chars.slice(index)].join(""));
      }
    }
    for (let index = 0; index < chars.length; index += 1) {
      candidates.add([...chars.slice(0, index), ...chars.slice(index + 1)].join(""));
      for (const char of alphabet) {
        if (char !== chars[index]) {
          candidates.add([...chars.slice(0, index), char, ...chars.slice(index + 1)].join(""));
        }
      }
      if (index < chars.length - 1) {
        candidates.add([...chars.slice(0, index), chars[index + 1], chars[index], ...chars.slice(index + 2)].join(""));
      }
    }
    return candidates;
  }
  scoreSuggestion(word, candidate) {
    var _a;
    const lowerWord = word.toLocaleLowerCase();
    const lowerCandidate = candidate.toLocaleLowerCase();
    const distance = boundedLevenshteinDistance(lowerWord, lowerCandidate, 4);
    const lengthPenalty = Math.abs(Array.from(lowerWord).length - Array.from(lowerCandidate).length) * 0.25;
    const prefixBonus = lowerCandidate.startsWith((_a = lowerWord[0]) != null ? _a : "") ? -0.2 : 0;
    return distance + lengthPenalty + prefixBonus;
  }
  normalizeWord(word) {
    let normalized = word.trim();
    for (const ignored of this.affixes.ignoredChars) {
      normalized = normalized.split(ignored).join("");
    }
    return normalized;
  }
};
function parseAffixes(source) {
  var _a;
  const prefixes = /* @__PURE__ */ new Map();
  const suffixes = /* @__PURE__ */ new Map();
  const ignoredChars = /* @__PURE__ */ new Set();
  const replacements = [];
  const maps = [];
  let tryChars = [];
  let flagMode = "ASCII";
  const lines = source.split(/\r?\n/);
  for (let index = 0; index < lines.length; index += 1) {
    const line = cleanLine(lines[index]);
    if (!line) {
      continue;
    }
    const parts = line.split(/\s+/);
    if (parts[0] === "FLAG" && parts[1]) {
      flagMode = parts[1];
      continue;
    }
    if (parts[0] === "TRY" && parts[1]) {
      tryChars = Array.from(parts[1]);
      continue;
    }
    if (parts[0] === "MAP" && parts.length === 2 && !/^\d+$/.test(parts[1])) {
      maps.push(Array.from(parts[1]));
      continue;
    }
    if (parts[0] === "REP" && parts.length >= 3 && !/^\d+$/.test(parts[1])) {
      replacements.push({
        from: unescapeAffixPattern(parts[1]),
        to: unescapeAffixPattern(parts[2])
      });
      continue;
    }
    if (parts[0] === "IGNORE" && parts[1]) {
      for (const char of Array.from(parts[1])) {
        ignoredChars.add(char);
      }
      continue;
    }
    if ((parts[0] === "PFX" || parts[0] === "SFX") && parts.length >= 4 && /^\d+$/.test(parts[3])) {
      const type = parts[0];
      const flag = parts[1];
      const crossProduct = parts[2] === "Y";
      const count = Number(parts[3]);
      const target = type === "PFX" ? prefixes : suffixes;
      const rules = (_a = target.get(flag)) != null ? _a : [];
      for (let offset = 1; offset <= count && index + offset < lines.length; offset += 1) {
        const ruleLine = cleanLine(lines[index + offset]);
        const ruleParts = ruleLine.split(/\s+/);
        if (ruleParts[0] !== type || ruleParts[1] !== flag || ruleParts.length < 5) {
          continue;
        }
        rules.push({
          flag,
          type,
          crossProduct,
          strip: ruleParts[2] === "0" ? "" : unescapeHunspellValue(ruleParts[2]),
          add: stripAffixFlags(ruleParts[3] === "0" ? "" : unescapeHunspellValue(ruleParts[3])),
          condition: conditionToRegExp(ruleParts[4], type)
        });
      }
      target.set(flag, rules);
      index += count;
    }
  }
  return { flagMode, prefixes, suffixes, ignoredChars, replacements, maps, tryChars };
}
function parseDictionary(source, flagMode) {
  var _a, _b, _c;
  const lines = source.split(/\r?\n/);
  const words = [];
  const start = /^\d+$/.test((_b = (_a = lines[0]) == null ? void 0 : _a.trim()) != null ? _b : "") ? 1 : 0;
  for (let index = start; index < lines.length; index += 1) {
    const line = cleanLine(lines[index]);
    if (!line) {
      continue;
    }
    const separatorIndex = findFlagSeparator(line);
    if (separatorIndex === -1) {
      words.push({ word: line, flags: [] });
      continue;
    }
    const word = line.slice(0, separatorIndex);
    const rawFlags = (_c = line.slice(separatorIndex + WORD_SEPARATOR.length).split(/\s+/)[0]) != null ? _c : "";
    words.push({ word, flags: parseFlags(rawFlags, flagMode) });
  }
  return words;
}
function parseFlags(flags, mode) {
  var _a;
  if (!flags) {
    return [];
  }
  if (mode === "UTF-8" || mode === "ASCII") {
    return Array.from(flags);
  }
  if (mode === "LONG") {
    return (_a = flags.match(/.{1,2}/g)) != null ? _a : [];
  }
  return flags.split(",");
}
function conditionToRegExp(condition, type) {
  const normalized = condition === "." ? ".*" : condition;
  return new RegExp(type === "SFX" ? `${normalized}$` : `^${normalized}`, "u");
}
function stripAffixFlags(value) {
  const separatorIndex = value.indexOf(WORD_SEPARATOR);
  return separatorIndex === -1 ? value : value.slice(0, separatorIndex);
}
function findFlagSeparator(line) {
  for (let index = 1; index < line.length; index += 1) {
    if (line[index] === WORD_SEPARATOR && line[index - 1] !== "\\") {
      return index;
    }
  }
  return -1;
}
function cleanLine(line) {
  if (!line) {
    return "";
  }
  return line.replace(/\s+#.*$/, "").trim();
}
function unescapeHunspellValue(value) {
  return value.replace(/\\\//g, WORD_SEPARATOR);
}
function unescapeAffixPattern(value) {
  return value.replace(/_/g, " ").replace(/\\\//g, WORD_SEPARATOR);
}
function addStringReplacementCandidates(candidates, word, from, to) {
  if (!from || !word.includes(from)) {
    return;
  }
  let index = word.indexOf(from);
  while (index !== -1) {
    candidates.add(`${word.slice(0, index)}${to}${word.slice(index + from.length)}`);
    index = word.indexOf(from, index + 1);
  }
}
function defaultTryChars() {
  return Array.from("abcdefghijklmnopqrstuvwxyz\xE1\xE0\xE3\xE2\xE9\xEA\xED\xF3\xF5\xF4\xFA\xFC\xE7");
}
function applyOriginalCasing(original, suggestion) {
  var _a, _b;
  if (/^[A-ZÁÀÂÃÉÊÍÓÔÕÚÜÇ]+$/u.test(original)) {
    return suggestion.toLocaleUpperCase();
  }
  if (/^[A-ZÁÀÂÃÉÊÍÓÔÕÚÜÇ]/u.test(original)) {
    const chars = Array.from(suggestion);
    return `${(_b = (_a = chars[0]) == null ? void 0 : _a.toLocaleUpperCase()) != null ? _b : ""}${chars.slice(1).join("")}`;
  }
  return suggestion;
}
function preserveCharCasing(original, replacement) {
  return original === original.toLocaleUpperCase() ? replacement.toLocaleUpperCase() : replacement.toLocaleLowerCase();
}
function boundedLevenshteinDistance(left, right, maxDistance) {
  const leftChars = Array.from(left);
  const rightChars = Array.from(right);
  if (Math.abs(leftChars.length - rightChars.length) > maxDistance) {
    return maxDistance + 1;
  }
  const previous = Array.from({ length: rightChars.length + 1 }, (_, index) => index);
  const current = new Array(rightChars.length + 1);
  for (let leftIndex = 1; leftIndex <= leftChars.length; leftIndex += 1) {
    current[0] = leftIndex;
    let colMin = current[0];
    for (let rightIndex = 1; rightIndex <= rightChars.length; rightIndex += 1) {
      const substitutionCost = leftChars[leftIndex - 1] === rightChars[rightIndex - 1] ? 0 : 1;
      current[rightIndex] = Math.min(previous[rightIndex] + 1, current[rightIndex - 1] + 1, previous[rightIndex - 1] + substitutionCost);
      colMin = Math.min(colMin, current[rightIndex]);
    }
    if (colMin > maxDistance) {
      return maxDistance + 1;
    }
    for (let index = 0; index < previous.length; index += 1) {
      previous[index] = current[index];
    }
  }
  return previous[rightChars.length];
}

// src/tokenize.ts
var WORD_PATTERN = /[\p{L}\p{M}]+(?:['’.-][\p{L}\p{M}]+)*/gu;
function tokenize(text) {
  const tokens = [];
  WORD_PATTERN.lastIndex = 0;
  let match;
  while ((match = WORD_PATTERN.exec(text)) !== null) {
    if (!/^\d+$/.test(match[0])) {
      tokens.push({
        text: match[0],
        from: match.index,
        to: match.index + match[0].length
      });
    }
  }
  return tokens;
}

// src/utils.ts
var LRUCache = class {
  constructor(maxSize = 1e4) {
    this.cache = /* @__PURE__ */ new Map();
    this.maxSize = maxSize;
  }
  get(key) {
    return this.cache.get(key);
  }
  set(key, value) {
    if (this.cache.size >= this.maxSize) {
      this.cache.clear();
    }
    this.cache.set(key, value);
  }
  clear() {
    this.cache.clear();
  }
};

// src/ui.ts
var import_obsidian = require("obsidian");
var TextEditorModal = class extends import_obsidian.Modal {
  constructor(app, title, content, onSave) {
    super(app);
    this.textArea = null;
    this.title = title;
    this.content = content;
    this.onSave = onSave;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: this.title });
    this.textArea = new import_obsidian.TextAreaComponent(contentEl).setValue(this.content).onChange((value) => {
      this.content = value;
    });
    this.textArea.inputEl.style.width = "100%";
    this.textArea.inputEl.style.minHeight = "300px";
    this.textArea.inputEl.style.resize = "vertical";
    const buttonContainer = contentEl.createEl("div", {
      attr: { style: "display: flex; justify-content: flex-end; gap: 8px; margin-top: 16px;" }
    });
    const cancelBtn = buttonContainer.createEl("button", { text: "Cancel" });
    cancelBtn.addEventListener("click", () => this.close());
    const saveBtn = buttonContainer.createEl("button", {
      text: "Save",
      cls: "mod-cta"
    });
    saveBtn.addEventListener("click", async () => {
      await this.onSave(this.content);
      this.close();
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};
var ConfirmationModal = class extends import_obsidian.Modal {
  constructor(app, title, message, onConfirm) {
    super(app);
    this.title = title;
    this.message = message;
    this.onConfirm = onConfirm;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: this.title });
    contentEl.createEl("p", { text: this.message });
    const buttonContainer = contentEl.createEl("div", {
      attr: { style: "display: flex; justify-content: flex-end; gap: 8px; margin-top: 24px;" }
    });
    const cancelBtn = buttonContainer.createEl("button", { text: "Cancel" });
    cancelBtn.addEventListener("click", () => this.close());
    const confirmBtn = buttonContainer.createEl("button", {
      text: "Confirm",
      cls: "mod-warning"
    });
    confirmBtn.addEventListener("click", () => {
      this.onConfirm();
      this.close();
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/main.ts
var MIN_WORD_LENGTH = 2;
var CUSTOM_DICTIONARY_FILENAME = "custom_dictionary.txt";
var IGNORED_WORDS_FILENAME = "ignored_words.txt";
var DEFAULT_SETTINGS = {
  activeLanguage: "pt-BR",
  languages: [{
    id: "pt-BR",
    name: "Portuguese (Brazil)",
    affPath: "languages/pt-BR.aff",
    dicPath: "languages/pt-BR.dic"
  }],
  enabled: true
};
var forceUpdateEffect = import_state.StateEffect.define();
var HunspellSpellcheckerPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.dictionary = null;
    this.ignoredWords = /* @__PURE__ */ new Set();
    this.customDictionaryWords = /* @__PURE__ */ new Set();
    this.statusBar = null;
    this.shouldFlagWordCache = new LRUCache(1e4);
    this.suggestionsCache = new LRUCache(2e3);
    this.dictionaryLoadPromise = null;
    this.unloaded = false;
  }
  async onload() {
    this.unloaded = false;
    await this.loadSettings();
    this.statusBar = this.addStatusBarItem();
    this.statusBar.setText("Hunspell: disabled");
    this.statusBar.classList.add("hunspell-status-bar-item");
    this.registerDomEvent(this.statusBar, "click", (event) => {
      if (!this.settings.enabled || this.settings.languages.length <= 1)
        return;
      const menu = new import_obsidian2.Menu();
      for (const language of this.settings.languages) {
        menu.addItem((item) => {
          item.setTitle(language.name).setChecked(language.id === this.settings.activeLanguage).onClick(async () => {
            this.settings.activeLanguage = language.id;
            await this.saveSettings();
            await this.reloadDictionary();
          });
        });
      }
      menu.showAtMouseEvent(event);
    });
    if (!this.settings.enabled) {
      return;
    }
    this.statusBar.setText("Hunspell: waiting");
    this.registerEditorExtension(this.createSpellcheckExtension());
    this.addSettingTab(new SpellcheckerSettingTab(this.app, this));
    this.addCommand({
      id: "reload-dictionary",
      name: "Reload dictionary",
      callback: () => this.reloadDictionary()
    });
    this.addCommand({
      id: "ignore-selected-word",
      name: "Ignore selected word",
      editorCallback: async (editor) => {
        const selected = editor.getSelection().trim();
        if (!selected) {
          new import_obsidian2.Notice("Select a word to ignore.");
          return;
        }
        await this.ignoreWord(selected);
      }
    });
    this.addCommand({
      id: "add-word-to-dictionary",
      name: "Add word to dictionary",
      editorCallback: async (editor) => {
        const selected = editor.getSelection().trim();
        if (!selected) {
          new import_obsidian2.Notice("Select a word to add.");
          return;
        }
        await this.addWordToDictionary(selected);
      }
    });
    this.registerEvent(this.app.workspace.on("editor-menu", (menu, editor) => {
      this.addContextMenuItems(menu, editor);
    }));
    await this.loadWordList(CUSTOM_DICTIONARY_FILENAME, this.customDictionaryWords);
    await this.loadWordList(IGNORED_WORDS_FILENAME, this.ignoredWords);
    void this.ensureDictionaryLoaded();
  }
  onunload() {
    this.unloaded = true;
  }
  async loadSettings() {
    var _a;
    const loaded = await this.loadData();
    this.settings = {
      ...DEFAULT_SETTINGS,
      ...loaded,
      languages: ((_a = loaded == null ? void 0 : loaded.languages) == null ? void 0 : _a.length) ? loaded.languages : DEFAULT_SETTINGS.languages,
      enabled: (loaded == null ? void 0 : loaded.enabled) !== false
    };
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.refreshEditors();
  }
  async reloadDictionary(options = {}) {
    if (this.dictionaryLoadPromise) {
      return this.dictionaryLoadPromise;
    }
    this.dictionaryLoadPromise = this.performDictionaryReload(options).finally(() => {
      this.dictionaryLoadPromise = null;
    });
    return this.dictionaryLoadPromise;
  }
  shouldFlagWord(word) {
    if (!this.dictionary || !this.settings.enabled) {
      return false;
    }
    const cached = this.shouldFlagWordCache.get(word);
    if (cached !== void 0) {
      return cached;
    }
    const normalized = word.toLocaleLowerCase();
    const shouldFlag = word.length >= MIN_WORD_LENGTH && !this.ignoredWords.has(normalized) && !this.customDictionaryWords.has(normalized) && !/^[A-ZÁÀÂÃÉÊÍÓÔÕÚÜÇ]{2,}$/u.test(word) && !this.dictionary.has(word);
    this.shouldFlagWordCache.set(word, shouldFlag);
    return shouldFlag;
  }
  suggest(word, limit = 8) {
    var _a;
    if (!this.dictionary) {
      return [];
    }
    const cached = this.suggestionsCache.get(word);
    if (cached !== void 0) {
      return cached;
    }
    const suggestions = new Set((_a = this.dictionary.suggest(word, limit)) != null ? _a : []);
    for (const suggestion of this.suggestCustomDictionaryWords(word, limit)) {
      suggestions.add(suggestion);
    }
    const result = Array.from(suggestions).slice(0, limit);
    this.suggestionsCache.set(word, result);
    return result;
  }
  async ignoreWord(word) {
    const normalized = normalizeCustomDictionaryWord(word);
    if (!normalized)
      return;
    if (!this.ignoredWords.has(normalized)) {
      this.ignoredWords.add(normalized);
      await this.saveWordList(IGNORED_WORDS_FILENAME, this.ignoredWords);
      this.shouldFlagWordCache.clear();
      this.refreshEditors();
    }
    new import_obsidian2.Notice(`"${word}" will be ignored.`);
  }
  async addWordToDictionary(word) {
    const normalized = normalizeCustomDictionaryWord(word);
    if (!normalized) {
      return;
    }
    if (!this.customDictionaryWords.has(normalized)) {
      this.customDictionaryWords.add(normalized);
      await this.saveWordList(CUSTOM_DICTIONARY_FILENAME, this.customDictionaryWords);
      this.shouldFlagWordCache.clear();
      this.suggestionsCache.clear();
      this.refreshEditors();
    }
    new import_obsidian2.Notice(`"${word}" added to personal dictionary.`);
  }
  async refreshAvailableLanguages() {
    const discoveredLanguages = await this.discoverDictionaryLanguages();
    if (!discoveredLanguages.length) {
      return;
    }
    this.settings.languages = discoveredLanguages;
    if (!this.settings.languages.some((language) => language.id === this.settings.activeLanguage)) {
      this.settings.activeLanguage = this.settings.languages[0].id;
    }
  }
  async loadWordList(filename, set) {
    set.clear();
    try {
      const content = await this.readPluginFileSafe(filename);
      for (const word of parseCustomDictionary(content)) {
        set.add(word);
      }
    } catch (error) {
      console.warn(`Error loading list ${filename}: ${String(error)}`);
    }
    this.shouldFlagWordCache.clear();
  }
  async saveWordList(filename, set) {
    const words = Array.from(set).sort((left, right) => left.localeCompare(right));
    await this.ensurePluginDirectory();
    await this.writePluginFile(filename, words.length ? `${words.join("\n")}
` : "");
  }
  async readPluginFileSafe(filePath) {
    const fullPath = this.getPluginPath(filePath);
    if (await this.app.vault.adapter.exists(fullPath)) {
      return this.app.vault.adapter.read(fullPath);
    }
    return "";
  }
  async writePluginFile(filePath, content) {
    return this.app.vault.adapter.write(this.getPluginPath(filePath), content);
  }
  async deletePluginFile(filePath) {
    const fullPath = this.getPluginPath(filePath);
    if (await this.app.vault.adapter.exists(fullPath)) {
      return this.app.vault.adapter.remove(fullPath);
    }
  }
  getPluginPath(filePath = "") {
    return (0, import_obsidian2.normalizePath)(`${this.app.vault.configDir}/plugins/${this.manifest.id}/${filePath}`);
  }
  refreshEditors() {
    var _a, _b;
    (_b = (_a = this.app.workspace).updateOptions) == null ? void 0 : _b.call(_a);
    this.app.workspace.iterateAllLeaves((leaf) => {
      const view = leaf.view;
      if (view && view.editor && view.editor.cm) {
        const cm = view.editor.cm;
        if (cm.dispatch) {
          cm.dispatch({
            effects: forceUpdateEffect.of(null)
          });
        }
      }
    });
  }
  async performDictionaryReload(options = {}) {
    var _a, _b, _c, _d;
    await this.refreshAvailableLanguages();
    const language = this.getActiveLanguage();
    if (!language) {
      this.dictionary = null;
      this.shouldFlagWordCache.clear();
      this.suggestionsCache.clear();
      (_a = this.statusBar) == null ? void 0 : _a.setText("Hunspell: no language");
      if (!options.silent) {
        new import_obsidian2.Notice("No active language configured.");
      }
      this.refreshEditors();
      return;
    }
    try {
      (_b = this.statusBar) == null ? void 0 : _b.setText(`Hunspell: loading ${language.id}...`);
      const [aff, dic] = await Promise.all([this.readPluginFileSafe(language.affPath), this.readPluginFileSafe(language.dicPath)]);
      if (!aff || !dic) {
        throw new Error("Missing .aff or .dic files");
      }
      this.dictionary = await HunspellDictionary.fromFiles({ aff, dic }, (msg) => {
        var _a2;
        if (!this.unloaded) {
          (_a2 = this.statusBar) == null ? void 0 : _a2.setText(`Hunspell: ${msg}`);
        }
      });
      this.shouldFlagWordCache.clear();
      this.suggestionsCache.clear();
      (_c = this.statusBar) == null ? void 0 : _c.setText(`Hunspell: ${language.id}`);
      if (!options.silent) {
        new import_obsidian2.Notice(`Dictionary ${language.name} loaded.`);
      }
    } catch (error) {
      console.error("Error loading dictionary:", error);
      this.dictionary = null;
      this.shouldFlagWordCache.clear();
      this.suggestionsCache.clear();
      (_d = this.statusBar) == null ? void 0 : _d.setText("Hunspell: error");
      if (!options.silent) {
        new import_obsidian2.Notice(`Error loading dictionary: ${String(error)}`);
      }
    }
    this.refreshEditors();
  }
  async ensureDictionaryLoaded() {
    if (this.dictionary !== null || this.dictionaryLoadPromise) {
      return;
    }
    await this.reloadDictionary({ silent: true });
  }
  suggestCustomDictionaryWords(word, limit) {
    const normalized = normalizeCustomDictionaryWord(word);
    if (!normalized || !this.customDictionaryWords.size) {
      return [];
    }
    return Array.from(this.customDictionaryWords).map((candidate) => ({
      candidate,
      distance: boundedLevenshteinDistance(normalized, candidate, 2)
    })).filter(({ distance }) => distance <= 2).sort((left, right) => left.distance - right.distance || left.candidate.localeCompare(right.candidate)).slice(0, limit).map(({ candidate }) => candidate);
  }
  addContextMenuItems(menu, editor) {
    const range = this.getContextWordRange(editor);
    if (!range) {
      return;
    }
    const word = editor.getRange(range.from, range.to);
    if (!this.shouldFlagWord(word)) {
      return;
    }
    menu.addSeparator();
    if (import_obsidian2.Platform.isDesktop) {
      const suggestions = this.suggest(word, 6);
      if (suggestions.length > 0) {
        for (const suggestion of suggestions) {
          menu.addItem((item) => {
            item.setTitle(suggestion).setSection("hunspell-spellchecker").onClick(() => {
              editor.replaceRange(suggestion, range.from, range.to);
            });
          });
        }
        menu.addSeparator();
      }
    }
    menu.addItem((item) => {
      item.setTitle(`Ignore "${word}"`).setIcon("eye-off").setSection("hunspell-spellchecker").onClick(() => {
        void this.ignoreWord(word);
      });
    });
    menu.addItem((item) => {
      item.setTitle(`Add "${word}" to dictionary`).setIcon("book-plus").setSection("hunspell-spellchecker").onClick(() => {
        void this.addWordToDictionary(word);
      });
    });
  }
  getContextWordRange(editor) {
    if (editor.somethingSelected()) {
      return {
        from: editor.getCursor("from"),
        to: editor.getCursor("to")
      };
    }
    return editor.wordAt(editor.getCursor());
  }
  getActiveLanguage() {
    return this.settings.languages.find((language) => language.id === this.settings.activeLanguage);
  }
  async discoverDictionaryLanguages() {
    try {
      const languagesPath = this.getPluginPath("languages");
      if (!await this.app.vault.adapter.exists(languagesPath)) {
        await this.app.vault.adapter.mkdir(languagesPath);
      }
      const listedFiles = await this.app.vault.adapter.list(languagesPath);
      const entries = listedFiles.files.map((file) => getFileName(file));
      const dicIds = new Set(entries.filter((entry) => entry.endsWith(".dic")).map((entry) => removeFileExtension(entry)));
      let displayNames = null;
      try {
        displayNames = new Intl.DisplayNames(["en"], { type: "language" });
      } catch (e) {
      }
      return entries.filter((entry) => entry.endsWith(".aff")).map((entry) => removeFileExtension(entry)).filter((id) => dicIds.has(id)).sort((left, right) => left.localeCompare(right)).map((id) => {
        var _a;
        let name = id;
        if (displayNames) {
          try {
            const normalizedId = id.replace("_", "-");
            name = (_a = displayNames.of(normalizedId)) != null ? _a : id;
          } catch (e) {
          }
        }
        return {
          id,
          name,
          affPath: `languages/${id}.aff`,
          dicPath: `languages/${id}.dic`
        };
      });
    } catch (e) {
      return [];
    }
  }
  async ensurePluginDirectory() {
    const directoryPath = this.getPluginPath();
    if (!await this.app.vault.adapter.exists(directoryPath)) {
      await this.app.vault.adapter.mkdir(directoryPath);
    }
  }
  createSpellcheckExtension() {
    return createSpellcheckExtension(this);
  }
};
function createSpellcheckExtension(plugin) {
  const decorations = import_view.ViewPlugin.define((view) => {
    let decorations2 = buildDecorations(view, plugin);
    return {
      get decorations() {
        return decorations2;
      },
      update(update) {
        const hasForceUpdate = update.transactions.some((tr) => tr.effects.some((e) => e.is(forceUpdateEffect)));
        if (update.docChanged || update.viewportChanged || hasForceUpdate) {
          decorations2 = buildDecorations(update.view, plugin);
        }
      }
    };
  }, {
    decorations: (value) => value.decorations
  });
  const extensions = [decorations];
  if (import_obsidian2.Platform.isDesktop) {
    const suggestions = (0, import_view.hoverTooltip)((view, pos) => buildSuggestionTooltip(view, pos, plugin), {
      hoverTime: 300,
      hideOnChange: true
    });
    extensions.push(suggestions);
  }
  return extensions;
}
function buildDecorations(view, plugin) {
  if (!plugin.settings.enabled || !plugin.dictionary) {
    return new import_state.RangeSetBuilder().finish();
  }
  const builder = new import_state.RangeSetBuilder();
  const doc = view.state.doc;
  for (const { from, to } of view.visibleRanges) {
    let pos = from;
    while (pos <= to) {
      const line = doc.lineAt(pos);
      const text = line.text;
      for (const token of tokenize(text)) {
        if (plugin.shouldFlagWord(token.text)) {
          builder.add(line.from + token.from, line.from + token.to, import_view.Decoration.mark({ class: "hunspell-spellchecker-error" }));
        }
      }
      pos = line.to + 1;
    }
  }
  return builder.finish();
}
function buildSuggestionTooltip(view, pos, spellchecker) {
  const token = findMisspelledTokenAt(view, pos, spellchecker);
  if (!token) {
    return null;
  }
  const suggestions = spellchecker.suggest(token.text, 6);
  if (!suggestions.length) {
    return null;
  }
  return {
    pos: token.from,
    end: token.to,
    above: false,
    arrow: false,
    create: () => {
      const dom = document.createElement("div");
      dom.className = "hunspell-spellchecker-tooltip";
      for (const suggestion of suggestions) {
        const button = dom.createEl("button", { text: suggestion });
        button.addEventListener("mousedown", (event) => {
          event.preventDefault();
        });
        button.addEventListener("click", () => {
          view.dispatch({
            changes: { from: token.from, to: token.to, insert: suggestion }
          });
          view.focus();
        });
      }
      return { dom };
    }
  };
}
function findMisspelledTokenAt(view, pos, spellchecker) {
  const line = view.state.doc.lineAt(pos);
  for (const token of tokenize(line.text)) {
    const from = line.from + token.from;
    const to = line.from + token.to;
    if (from <= pos && pos <= to && spellchecker.shouldFlagWord(token.text)) {
      return { text: token.text, from, to };
    }
  }
  return null;
}
function normalizeCustomDictionaryWord(word) {
  return word.trim().toLocaleLowerCase().normalize("NFD");
}
function parseCustomDictionary(content) {
  return content.split(/\r?\n/).map((line) => line.trim()).filter((line) => line && !line.startsWith("#")).map(normalizeCustomDictionaryWord);
}
function getFileName(path) {
  var _a;
  return (_a = path.split("/").pop()) != null ? _a : "";
}
function removeFileExtension(fileName) {
  const index = fileName.lastIndexOf(".");
  return index === -1 ? fileName : fileName.slice(0, index);
}
var SpellcheckerSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    this.containerEl.empty();
    this.containerEl.createEl("h2", { text: "Hunspell Spellchecker" });
    new import_obsidian2.Setting(this.containerEl).setName("Active language").setDesc("Select the language for spell checking").addDropdown((dropdown) => {
      for (const language of this.plugin.settings.languages) {
        dropdown.addOption(language.id, language.name);
      }
      return dropdown.setValue(this.plugin.settings.activeLanguage).onChange(async (value) => {
        this.plugin.settings.activeLanguage = value;
        await this.plugin.saveSettings();
        await this.plugin.reloadDictionary();
        this.display();
      });
    });
    this.containerEl.createEl("h3", { text: "Installed Languages" });
    const langContainer = this.containerEl.createEl("div", { cls: "hunspell-language-list" });
    for (const language of this.plugin.settings.languages) {
      const item = langContainer.createEl("div", { cls: "hunspell-language-item" });
      const info = item.createEl("div", { cls: "hunspell-language-info" });
      info.createEl("span", { text: language.name, cls: "hunspell-language-name" });
      info.createEl("span", { text: language.id, cls: "hunspell-language-id" });
      const actions = item.createEl("div", { cls: "hunspell-language-actions" });
      if (this.plugin.settings.languages.length > 1) {
        const deleteBtn = actions.createEl("button", { text: "\u2715", cls: "mod-warning" });
        deleteBtn.title = "Delete language";
        deleteBtn.addEventListener("click", () => {
          if (this.plugin.settings.languages.length <= 1)
            return;
          new ConfirmationModal(this.app, "Delete language", `Are you sure you want to delete the files for "${language.name}"? This action cannot be undone.`, async () => {
            try {
              await this.plugin.deletePluginFile(language.affPath);
              await this.plugin.deletePluginFile(language.dicPath);
              await this.plugin.refreshAvailableLanguages();
              if (this.plugin.settings.activeLanguage === language.id && this.plugin.settings.languages.length > 0) {
                this.plugin.settings.activeLanguage = this.plugin.settings.languages[0].id;
                await this.plugin.reloadDictionary();
              }
              await this.plugin.saveSettings();
              this.display();
            } catch (e) {
              new import_obsidian2.Notice(`Error deleting language: ${String(e)}`);
            }
          }).open();
        });
      }
    }
    const addLangBtn = this.containerEl.createEl("button", {
      text: "Add Language",
      cls: "mod-cta hunspell-add-language-btn"
    });
    addLangBtn.addEventListener("click", () => {
      const input = document.createElement("input");
      input.type = "file";
      input.multiple = true;
      input.onchange = async (event) => {
        const target = event.target;
        const files = target.files;
        if (!files || files.length === 0)
          return;
        let affFile;
        let dicFile;
        for (let i = 0; i < files.length; i++) {
          if (files[i].name.endsWith(".aff"))
            affFile = files[i];
          if (files[i].name.endsWith(".dic"))
            dicFile = files[i];
        }
        if (!affFile || !dicFile) {
          new import_obsidian2.Notice("Please select both .aff and .dic corresponding files.");
          return;
        }
        const affName = removeFileExtension(affFile.name);
        const dicName = removeFileExtension(dicFile.name);
        if (affName !== dicName) {
          new import_obsidian2.Notice("The names of the selected .aff and .dic files do not match.");
          return;
        }
        try {
          const langsPath = this.plugin.getPluginPath("languages");
          if (!await this.app.vault.adapter.exists(langsPath)) {
            await this.app.vault.adapter.mkdir(langsPath);
          }
          const affContent = await affFile.arrayBuffer();
          const dicContent = await dicFile.arrayBuffer();
          await this.app.vault.adapter.writeBinary(this.plugin.getPluginPath(`languages/${affFile.name}`), affContent);
          await this.app.vault.adapter.writeBinary(this.plugin.getPluginPath(`languages/${dicFile.name}`), dicContent);
          await this.plugin.refreshAvailableLanguages();
          await this.plugin.saveSettings();
          new import_obsidian2.Notice(`Language ${affName} added successfully!`);
          this.display();
        } catch (err) {
          new import_obsidian2.Notice(`Error saving files: ${String(err)}`);
        }
      };
      input.click();
    });
    this.containerEl.createEl("hr");
    this.containerEl.createEl("h3", { text: "Personal Dictionary" });
    this.containerEl.createEl("p", {
      text: "Words you have added to your dictionary via right-click to be accepted during verification.",
      cls: "setting-item-description"
    });
    const customDictButtons = this.containerEl.createEl("div", {
      attr: { style: "display: flex; gap: 8px; margin-top: 8px;" }
    });
    const editCustomBtn = customDictButtons.createEl("button", { text: "Edit File" });
    editCustomBtn.addEventListener("click", async () => {
      const content = await this.plugin.readPluginFileSafe(CUSTOM_DICTIONARY_FILENAME);
      new TextEditorModal(this.app, "Edit Personal Dictionary", content, async (newContent) => {
        await this.plugin.writePluginFile(CUSTOM_DICTIONARY_FILENAME, newContent);
        await this.plugin.loadWordList(CUSTOM_DICTIONARY_FILENAME, this.plugin.customDictionaryWords);
        this.plugin.refreshEditors();
        new import_obsidian2.Notice("Personal dictionary updated.");
      }).open();
    });
    const clearCustomBtn = customDictButtons.createEl("button", { text: "Clear All", cls: "mod-warning" });
    clearCustomBtn.addEventListener("click", () => {
      new ConfirmationModal(this.app, "Clear Personal Dictionary", "Are you sure you want to delete all words from your personal dictionary? This action cannot be undone.", async () => {
        this.plugin.customDictionaryWords.clear();
        await this.plugin.saveWordList(CUSTOM_DICTIONARY_FILENAME, this.plugin.customDictionaryWords);
        this.plugin.refreshEditors();
        new import_obsidian2.Notice("Personal dictionary cleared.");
      }).open();
    });
    this.containerEl.createEl("hr");
    this.containerEl.createEl("h3", { text: "Ignored Words" });
    this.containerEl.createEl("p", {
      text: "Words you have asked the spellchecker to ignore locally.",
      cls: "setting-item-description"
    });
    const ignoredWordsButtons = this.containerEl.createEl("div", {
      attr: { style: "display: flex; gap: 8px; margin-top: 8px;" }
    });
    const editIgnoredBtn = ignoredWordsButtons.createEl("button", { text: "Edit File" });
    editIgnoredBtn.addEventListener("click", async () => {
      const content = await this.plugin.readPluginFileSafe(IGNORED_WORDS_FILENAME);
      new TextEditorModal(this.app, "Edit Ignored Words", content, async (newContent) => {
        await this.plugin.writePluginFile(IGNORED_WORDS_FILENAME, newContent);
        await this.plugin.loadWordList(IGNORED_WORDS_FILENAME, this.plugin.ignoredWords);
        this.plugin.refreshEditors();
        new import_obsidian2.Notice("Ignored words updated.");
      }).open();
    });
    const clearIgnoredBtn = ignoredWordsButtons.createEl("button", { text: "Clear All", cls: "mod-warning" });
    clearIgnoredBtn.addEventListener("click", () => {
      new ConfirmationModal(this.app, "Clear Ignored Words", "Are you sure you want to clear the list of all ignored words? The spellchecker will flag them again.", async () => {
        this.plugin.ignoredWords.clear();
        await this.plugin.saveWordList(IGNORED_WORDS_FILENAME, this.plugin.ignoredWords);
        this.plugin.refreshEditors();
        new import_obsidian2.Notice("Ignored words list cleared.");
      }).open();
    });
  }
};
