name: Release Plugin

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: Build plugin
        id: build
        run: |
          npm install
          npm run build

      - name: Upload assets to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -z "${{ github.event.release.tag_name }}" ]; then
            tag=$(git describe --tags --abbrev=0)
          else
            tag="${{ github.event.release.tag_name }}"
          fi
          
          echo "Uploading assets to tag: $tag"
          gh release upload "$tag" main.js manifest.json styles.css --clobber
          
      - name: Attest to build provenance for main
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: 'main.js'
          
      - name: Attest to build provenance for styles
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: 'styles.css'